import { decryptPayload, type EncryptedPayload } from '@/lib/decrypt';

// Encrypted essays, generated by scripts/encrypt-essay.mjs. Loaded lazily so the ciphertext
// is not part of the main bundle.
const payloads = import.meta.glob<EncryptedPayload>('../data/protected/*.json', { import: 'default' });

export const hasEssay = (slug: string) => `../data/protected/${slug}.json` in payloads;

export const decryptEssay = async (slug: string, password: string) =>
  decryptPayload(await payloads[`../data/protected/${slug}.json`](), password);

// One password per browser session, shared by all protected essays
const STORAGE_KEY = 'essay-pw';
export const storedPassword = () => {
  try { return sessionStorage.getItem(STORAGE_KEY); } catch { return null; }
};
export const storePassword = (pw: string) => {
  try { sessionStorage.setItem(STORAGE_KEY, pw); } catch { /* private mode etc. */ }
};
