import { useEffect, useState, type FormEvent } from 'react';
import { useParams, Navigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { EssayChart } from '@/components/EssayCharts';
import { decryptPayload, type EncryptedPayload } from '@/lib/decrypt';

// Encrypted essays, generated by scripts/encrypt-essay.mjs. Loaded lazily so the ciphertext
// is not part of the main bundle.
const payloads = import.meta.glob<EncryptedPayload>('../data/protected/*.json', { import: 'default' });
const loaderFor = (slug: string) => payloads[`../data/protected/${slug}.json`];

const slugify = (text: string) =>
  text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const storageKey =(slug: string) => `essay-pw:${slug}`;
const readStored = (slug: string) => {
  try { return sessionStorage.getItem(storageKey(slug)); } catch { return null; }
};
const store = (slug: string, pw: string) => {
  try { sessionStorage.setItem(storageKey(slug), pw); } catch { /* private mode etc. */ }
};

const ProtectedEssayPage = () => {
  const { slug = '' } = useParams<{ slug: string }>();
  const load = loaderFor(slug);
  const [content, setContent] = useState<string | null>(null);
  const [password, setPassword] = useState('');
  const [error, setError] = useState(false);
  const [busy, setBusy] = useState(false);

  const unlock = async (pw: string, remember: boolean) => {
    if (!load) return;
    setBusy(true);
    try {
      const text = await decryptPayload(await load(), pw);
      if (remember) store(slug, pw);
      setContent(text);
      setError(false);
    } catch {
      setError(true);
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    const saved = readStored(slug);
    if (saved) unlock(saved, false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug]);

  if (!load) return <Navigate to="/404" replace />;

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (password) unlock(password, true);
  };

  return (
    <div className="min-h-screen">
      <Header />
      <main className="pt-24">
        {content === null ? (
          <section className="section-padding">
            <div className="container-width">
              <form onSubmit={onSubmit} className="bp-panel max-w-md p-6 sm:p-8">
                <span className="bp-tick bp-tick-tl" />
                <span className="bp-tick bp-tick-tr" />
                <span className="bp-tick bp-tick-bl" />
                <span className="bp-tick bp-tick-br" />
                <span className="bp-kicker block mb-4">// restricted — draft</span>
                <h1 className="text-2xl font-bold text-white mb-2">This essay is password-protected.</h1>
                <p className="text-muted-foreground mb-6">Enter the password you were sent to read it.</p>
                <input
                  type="password"
                  autoFocus
                  value={password}
                  onChange={e => { setPassword(e.target.value); setError(false); }}
                  className="bp-mono w-full bg-white/[0.04] border border-border px-3 py-2.5 text-foreground outline-none focus:border-accent"
                  placeholder="password"
                  aria-label="Password"
                />
                {error && <p className="bp-mono text-xs text-[#ff8a7a] mt-2">Wrong password.</p>}
                <button type="submit" disabled={busy} className="bp-cta mt-5 disabled:opacity-60">
                  {busy ? 'Unlocking…' : 'Unlock'}
                </button>
              </form>
            </div>
          </section>
        ) : (
          <section className="section-padding">
            <article className="max-w-[68ch] mx-auto text-foreground/90 text-lg leading-relaxed">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  h1: ({ children }) => <h1 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-6">{children}</h1>,
                  h2: ({ children }) => (
                    <h2 id={slugify(String(children))} className="scroll-mt-24 text-2xl md:text-3xl font-bold text-white mt-14 mb-5 pt-6 border-t border-dashed border-border">{children}</h2>
                  ),
                  h3: ({ children }) => <h3 className="text-xl font-semibold text-white mt-8 mb-3">{children}</h3>,
                  p: ({ children }) => <p className="mb-5">{children}</p>,
                  strong: ({ children }) => <strong className="text-white font-semibold">{children}</strong>,
                  a: ({ href, children }) => {
                    const cls = 'text-accent underline decoration-accent/40 underline-offset-2 hover:decoration-accent transition-smooth';
                    // In-page anchors (e.g. links to the appendix) scroll instead of opening a new tab
                    if (href?.startsWith('#')) {
                      return (
                        <a href={href} className={cls} onClick={e => {
                          e.preventDefault();
                          document.getElementById(href.slice(1))?.scrollIntoView({ behavior: 'smooth' });
                        }}>
                          {children}
                        </a>
                      );
                    }
                    return <a href={href} target="_blank" rel="noopener noreferrer" className={cls}>{children}</a>;
                  },
                  blockquote: ({ children }) => (
                    <blockquote className="border-l-2 border-accent pl-5 my-8 text-xl text-white/95 [&_p]:mb-0">{children}</blockquote>
                  ),
                  ul: ({ children }) => <ul className="list-disc pl-6 mb-5 space-y-2">{children}</ul>,
                  ol: ({ children }) => <ol className="list-decimal pl-6 mb-5 space-y-2">{children}</ol>,
                  hr: () => <hr className="my-12 border-border border-dashed" />,
                  table: ({ children }) => (
                    <div className="overflow-x-auto my-8"><table className="bp-mono w-full text-sm border-collapse">{children}</table></div>
                  ),
                  th: ({ children }) => <th className="text-left text-accent font-normal uppercase tracking-[0.1em] text-xs border-b border-border py-2 pr-4">{children}</th>,
                  td: ({ children }) => <td className="border-b border-dotted border-border py-2 pr-4 align-top">{children}</td>,
                  img: ({ src, alt }) => (
                    <figure className="my-10">
                      <img src={src} alt={alt || ''} className="mx-auto max-w-full border border-border" />
                      {alt && <figcaption className="bp-mono text-[0.7rem] text-muted-foreground mt-3 text-center">{alt}</figcaption>}
                    </figure>
                  ),
                  // ```chart <id>``` fences render a native chart
                  code: ({ className, children }) => {
                    if (className === 'language-chart') return <EssayChart id={String(children).trim()} />;
                    return <code className="bp-mono text-[0.9em] bg-white/[0.06] px-1">{children}</code>;
                  },
                  pre: ({ children }) => <>{children}</>,
                }}
              >
                {content}
              </ReactMarkdown>
            </article>
          </section>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default ProtectedEssayPage;
